### ISSUE TITLE
Integrate KillOnDrop with ProcessGroup/ProcessSession

### ISSUE THREAD

**Issue by Yohe-Am** [watchexec/process-wrap#6]
We have a CLI program that spawns other commands and we'd like the full child tree to disappear before it dies (To prevent them from emitting to stderr after the CLI is done). The current KillOnDrop implementation relies only on tokio's semantics and doesn't take the sessions into consideration.

Willing to write a PR for this.

Edit: this might have been a misfile, sorry. Looking at the code, the process session implementation doesn't indeed take `KillOnDrop` into consideration but we're no longer blocked by this and the issue was elsewhere.

**Comment by passcod** [comment]
I'll close for now, but always happy to get PRs :)
